Jyaou/mongo setup
JyaouShingan/bili-bot pull request #12
Opened 2019-08-12 08:42 UTC by JyaouShingan

2019-08-12 12:12 UTC, TeakayAero requested changes

2019-08-12 12:12 UTC, TeakayAero commented on src/database/mongo-service.ts
> +export const MongoDB = new MongoDBService();
Do export default for files only have one class

2019-08-12 12:12 UTC, TeakayAero commented on src/app.ts
> +    if (await MongoDB.start()) {
false handle?

2019-08-12 12:12 UTC, TeakayAero commented on src/bilibili-api.ts
> +    const response = await request(req);
future: probably should type this

2019-08-12 12:12 UTC, TeakayAero commented on src/commands/load.ts
> +        for (const song of songs) {
future: threshold

2019-08-12 12:12 UTC, TeakayAero commented on src/commands/load.ts
>      private async load(message: Message, guild: GuildManager, collection?: string) {
TODO: migration script

2019-08-12 12:12 UTC, TeakayAero commented on src/commands/load.ts
> +        if (songs.length === 0) {
Any message handle?

2019-08-12 12:12 UTC, TeakayAero commented on src/commands/promote.ts
> +        if (isNaN(userIndex) || !Number.isInteger(userIndex)) {
Future: utilize this

2019-08-12 12:12 UTC, TeakayAero commented on src/commands/promote.ts
> +        const index = userIndex - 1;
?

make index a non-const solves this

2019-08-12 12:12 UTC, TeakayAero commented on src/database/guild-datasource.ts
> +        if (!this.db) {
log, error handle

2019-08-12 12:12 UTC, TeakayAero commented on src/database/guild-datasource.ts
> +        if (!this.db) {
make this as `setup`, do this.db check in functions, prevent using unneeded await every time

2019-08-12 12:12 UTC, TeakayAero commented on src/database/guild-datasource.ts
> +    private async getPlaylist(name: string, user: User, create: boolean = false) {
probably should specify return types

2019-08-12 12:12 UTC, TeakayAero commented on src/database/guild-datasource.ts
> +            return await new this.Playlist({
no return await in async functions

2019-08-12 12:12 UTC, TeakayAero commented on src/database/mongo-service.ts
> +    private uri: string = 'mongodb://localhost:27017';
config file

2019-08-12 12:12 UTC, TeakayAero commented on src/database/mongo-service.ts
> +        const connection = await this.client.createConnection(`${this.uri}/${database}`, {useNewUrlParser: true});
what does create Connection return on error?

2019-08-12 12:12 UTC, TeakayAero commented on src/database/schema.ts
> +import {Document, Schema} from "mongoose";
Future: separate this file pls.

db/schema/ ...
db/service/ ....

2019-08-13 03:58 UTC, JyaouShingan commented on src/app.ts
> +    if (await MongoDB.start()) {
no handle, exit program

2019-08-13 03:59 UTC, JyaouShingan commented on src/database/mongo-service.ts
> +        const connection = await this.client.createConnection(`${this.uri}/${database}`, {useNewUrlParser: true});
throw

2019-08-13 04:31 UTC, TeakayAero approved these changes

2019-08-13 04:31 UTC, merged